apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: staging-

labels:
  - pairs:
      environment: staging

patches:
  - path: deployment.yaml
  - path: service.yaml
