apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: windsurf-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/asyrawih/argo.git
    targetRevision: HEAD
    path: kustomize/overlays/production
  destination:
    server: https://localhost:6443
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
