apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argoproj.io/background
spec:
  project: default
  source:
    repoURL: https://github.com/asyrawih/argo.git
    targetRevision: HEAD
    path: kustomize/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
