apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    environment: production
    managed-by: kustomize
data:
  ENVIRONMENT: production
  SAMPLE: "This is a sample value in the production environment"
