apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: prod-

labels:
  - pairs:
      environment: production

patches:
  - path: deployment.yaml
  - path: service.yaml
  - path: configMap.yaml
