apiVersion: v1
kind: Service
metadata:
  name: app-service  # This must match the base service name
  labels:
    environment: production
spec:
  type: LoadBalancer  # Using LoadBalancer for production
  $patch: replace
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: app-deployment
