apiVersion: v1
kind: Service
metadata:
  name: app-deployment
  labels:
    environment: production
spec:
  ports:
  - port: 8080
    targetPort: 8080  # Adjust this to match your app's container port
    protocol: TCP
    name: http
