apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: my-app
    managed-by: kustomize
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: my-app
